model:
  name: soccer player class prediction
  author: Angela Chen
  version: A1
  description:
  tags:
    - classifier
  dependencies: requirements.txt
load_data:
  read_data: 
    path: data/data.csv
  upload_data:
    input_path: data/data.csv
    bucket_name: nw-sichen
    output_path: 423project/data.csv
  load_csv:
    path: data/data.csv
preprocess_data:
  generate_class: 
    target: Overall
    response: Class
  clean_data:
    drop: [ID, Name,Photo,Preferred.Foot,Nationality,Overall,Potential,Club,Position,Jersey.Number]
choose_features:
  select_feature: 
    path: data/clean_data.csv
    target: Class
train_data:
  split_data:
    path: data/model_data.csv
    test_size: 0.3
    target: Class
  train:
    method: decision_tree #choose method from logistic_regression, random_forest and decision_tree
evaluate_model:
  evaluate_model:
    modelpath: models/model.pkl
    xtestpath: data/xtest.csv
    ytestpath: data/ytest.csv



  

